export const directionsArray = [
    'Take 1 tablet by mouth once daily in the morning',
    'Take 1 tablet by mouth once daily in the evening',
    'Take 1 tablet by mouth once daily at bedtime',
    'Take 1 tablet by mouth twice daily',
    'Take 1 tablet by mouth three times daily',
    'Take 1 tablet by mouth four times daily',
    'Take 1 tablet by mouth every 6 hours',
    'Take 1 tablet by mouth every 8 hours',
    'Take 1 tablet by mouth every 12 hours',
    'Take 1 tablet by mouth every 4 hours',
    'Take 1 tablet by mouth every 6 hours as needed',
    'Take 1 tablet by mouth every 4 hours as needed',
    'Take 1 tablet by mouth every 8 hours as needed',
    'Take 1 tablet by mouth every 12 hours as needed',
    'Take 1 tablet by mouth every 2 hours as needed',
]